### ISSUE TITLE
你好请问一下可以进行overleaf编写吗

### ISSUE THREAD

**Issue by sumingfirst** [jiandahao/BIT-thesis-LaTex#2]

**Comment by shuibinlong** [comment]
当然可以

**Comment by sumingfirst** [comment]
你的邮件我受到非常感谢配合

**Comment by Flyforever-Tang** [comment]
使用overleaf的朋友，如果编译的时候出现类似

> “Critical Class ctexbook Error: CTeX fontset `fandol' is unavailable in”

的错误，可以点击页面左上角的overleaf图标，在**Settings-Compiler**里改成**XeLaTex**，就可以编译通过了~

**Comment by sumingfirst** [comment]
你的邮件我受到非常感谢配合
